---
title: "SANDWOODS"
---

-   A desert filled with cactuses

-   Amazonia uses this area for sand mining. Possibly for glass and concrete production.

A desert full of sand dunes created by the winds of the nearby WINDWOODS.

# Minor bases

## Solar tower

Solar power energy produced by mirrors focussing sun on a large tower. Charges up batteries. These batteries are transported to the other bases by the AIRBORNE DOPPELGANGERS and their tamed ADULT GIANT ANTLIONS.

A tower dungeon.

## Desalination base

Base where water is brought in from the sea and desalinated. Uses sun based evaporation. Water used for mining and consumption.

## Bonehead hatchery

Boneheads are Pachycephalosaurus. Throughout the desert they feed on cactus. They all lay their eggs at the hatchery. Doppelganger Dunes set up defences here to guard the eggs from predators. In exchange they take some eggs for nutrition, ensuring to leave enough for a healthy population.

The boneheads were created by the CGC in the WATERWOODS. They are like an invasive species, having destroyed a large amount of the cactuses

It is an open base guarded by towers and patrols.

# Major base

The major base is a sand extraction site.

It is heavily defended. It is a floating island stolen from the WINDWOODS.

Sand is separated into its various elements & compounds.

Goods, people, and energy flown in and out by Adult antlions. The SKYBOUND DOPPELGANGERS can get themselves on and off it.

## Defenses

-   4 Large laser cannon towers: 2 on top and 2 on bottom surface of island. If the solar tower has be sabotaged successfully only one of these will be functional, one at the top.
-   Doppelganger guards: There will be less guards if the desalination and bonehead base have been sabotaged. This is due to the redirecting of forces and that some of the forces will have to leave the DENDROSPHAERA as there is not enough provisions to maintain them all.

# Fauna and Flora

The three major fauna and flora of the SANDWOODS are cactuses, BONEHEADS, and Giant Antlions (GIANT LARVAL ANTLIONS and GIANT ADULT ANTLIONS).

The SANDWOODS was once covered in a forest of cactuses. Now there is only a scattering os smaller forests. This decimation was caused by the introduction of the BONEHEADS. The BONEHEADS eat the entire cactus but are especially fond of the special rare fruit the cactuses. This fruit can be used to easily tame and ride the BONEHEADS.

The BONEHEADS are [Pachycephalosaurus](https://en.wikipedia.org/wiki/Pachycephalosaurus) that were created by the [CGC](https://m-gemmell.github.io/Primeval_Deities_FIST/Gaia/CGC.html) scientists that occupy the [WATERWOODS](DENDROSPHAERA/WATERWOODS.qmd). As herbivores they generally gather in roaming flocks.

As the population of BONEHEADS has increased so has the population of Giant [Antlions](https://en.wikipedia.org/wiki/Antlion). The larvae bury into the sand around the cactuses and ambush the BONEHEADS. This has greatly increased the survival rates of the LARVAL GIANT ANTLIONS which are also able to eat humans. This has therefore increased the amount of ADULT GIANT ANTLIONS.

[DOPPELGANGER DUNES](https://m-gemmell.github.io/Primeval_Deities_FIST/Nyxmera/Doppelganger_Dunes.html) use the ADULT GIANT ANTLIONS as massive air-based beasts of burden. The [SKYBOUND DOPPELGANGERS](https://m-gemmell.github.io/Primeval_Deities_FIST/Nyxmera/Doppelganger_Dunes.html#skybound_doppelganger) are able to tame and escort them with their aeolian whistles. They are easy to maintain only needing to feed on airborne pollen that is blown in by the winds of the [WINDWOODS](DENDROSPHAERA/WINDWOODS.qmd). These strong winds also allowing the adults to easily fly despite their size.

## BONEHEADS

5 HP \| 1 ARMOR \| TAC:-1 \| FRC:+1 \| RFX:0 \| CRE:-1

- [Pachycephalosaurus](https://en.wikipedia.org/wiki/Pachycephalosaurus)
- Think bared skull (1D6+1 DAMAGE)
- Tough skin
- Herbivorous dinosaur
- Males have blue and yellow feathers
- Females have sand coloured feathers

__THICK-SKULLED:__ These creatures are dumb and skittish but they thrive in deserts. When threatened they have a 4 in 1D6 chance of fleeing. If they don't flee they will instead fight to the death.

## GIANT LARVAL ANTLION

4 HP \| TAC:-1 \| FRC:+1 \| RFX:+1 \| CRE:-2

- Larval [Antlion](https://en.wikipedia.org/wiki/Antlion) the size of a rhino
- Massive sickle-like jaws (1D6+2 DAMAGE)

__AVALANCHER:__ This creature burrows into the sand creating an area around it that will avalanche into its mouth with the weight of a human. As the creatures are large the avalanche area is wide and deep. Quick reactions and/or help from their team-mates may prevent being caught in the jaws of this deadly predator.

## GIANT ADULT ANTLION

6 HP \| TAC:0 \| FRC:0 \| RFX:+1 \| CRE:-1

- Adult [Antlion](https://en.wikipedia.org/wiki/Antlion) with the wingspan of a Boeing 757 (38m)
- Look similar to dragonflies

__WIND-POWERED:__ These massive creatures can only survive in high wind deserts. The wind keeps their massive size afloat and brings them the airborne pollen they need to survive.

# Doppelgänger Dunes

[Doppelgänger Dunes](https://m-gemmell.github.io/Primeval_Deities_FIST/Nyxmera/Doppelganger_Dunes.html) occupy the desert for Amazonia. They are Nyxmera faction that lives and works in deserts. They love the temperature extremes of day & night. They also adore the clearness of the skies so they can observe the day and night skies.

The leader of the Doppelganger Dunes forces is SOL: DOPPELGANGER OF DESERTS.

[Sol the Ablated](https://m-gemmell.github.io/Primeval_Deities_FIST/Nyxmera/Sol_the_ablated.html) is a lieutenant of [Dr. Petra Pufferfish](https://m-gemmell.github.io/Primeval_Deities_FIST/Gaia/Dr_Petra_Pufferfish.html).
Sol is able to implant their will into another human by replacing the victim's eyes with their own.
One eyes has blue sclera with a yellow iris whilst the other has black sclera with a purple and grey iris.
This human is then known as a Sol Doppelganger.

The Doppelganger still retains a lot of its personality but works whole heartedly to benefit Sol and will be called Sol.
It also gains powers related to given title by Sol.

# Encounters

When the characters travel through the SANDWOODS roll for an encounter.

- First roll a D6
  - On a 1-4 roll once on the encounter table. The players encounter that one group.
  - On a 5-6 roll twice (rerolling any duplicates). Both groups are meeting and the players are there whilst it happens.
  
1. Group of 1D6+1 orang-utans trying to escape to the WINDWOODS
2. A forest of cactuses. Destruction by BONEHEADS will be apparent around the edges.
3. 1D6 SKYBOUND DOPPELGANGERS escorting an ADULT ANTLION
4. 2D6 SANDBOUND DOPPELGANGERS
5. 3D6 BONEHEADS
6. Hidden LARVAL ANTLION

