project:
  type: website
editor: source

#Website
website:
  favicon: /images/THE_BEAD_favicon.png
  page-navigation: true
  title: "THE BEAD"
  description: "Multi dimensional advetures with the FIST RPG"
##Navbar
  navbar:
    title: THE BEAD
    logo: "images/THE_BEAD.png"
    collapse-below: lg
###Navbar left
    left:
      - text: "Overview"
        href: index.qmd
      - text: "RUSTLANDS"
        href: THE_RUSTLANDS/RUSTLANDS.qmd

###Navbar right
    right:
    # List of icons: https://icons.getbootstrap.com/
      - icon: cup
        href: https://ko-fi.com/waveofinspiration
        aria-label: Ko-fi
      - icon: github
        href: https://github.com/m-gemmell/THE_BEAD
        aria-label: GitHub
##Apge footer
  page-footer:
    left: |
      [![](https://licensebuttons.net/l/by-sa/4.0/88x31.png){fig-alt="CC BY-SA 4.0" height=30px}](https://creativecommons.org/licenses/by-sa/4.0/)
    center: |
      [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K6IRLA0)
    right: |
      [![](/images/FIST_compatibility_mark_cropped.png){fig-alt="FIST" height=40px}](https://claymorerpgs.itch.io/fist)
##Sidebar
  sidebar:
    - id: Overview
      title: "Overview"
      style: "floating"
      align: left
      contents:
        - href: index.qmd
    - id: RUSTLANDS
      title: "RUSTLANDS"
      style: "floating"
      align: left
      contents:
        - href: THE_RUSTLANDS/RUSTLANDS.qmd
        - href: THE_RUSTLANDS/FOODCHAIN.qmd
        - href: THE_RUSTLANDS/RUSTPLAINS.qmd
        - href: THE_RUSTLANDS/LEMAN_GROVE.qmd
        - href: THE_RUSTLANDS/WHALEFALL.qmd
        - href: THE_RUSTLANDS/THE_GARDEN.qmd
        - href: THE_RUSTLANDS/SKYSLIP.qmd
        - href: THE_RUSTLANDS/CATALOG.qmd

#Format
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 0.75em
    #HTML themes: https://quarto.org/docs/output-formats/html-themes.html
    theme: 
      dark: [cyborg, styles.scss]
      light: [cosmo, styles.scss]
    mainfont: Lexend
    toc: true