---
title: "Traits"
editor: 
  markdown: 
    wrap: sentence
---

Custom traits that players can use for their characters.
These are split up by which deity they most closely relate to.

They also relate to some optional rules for FIST.

The full list of traits in the base FIST can be seen at: [https://fistref.com/](https://fistref.com/)

## Nyxmera

__CHANCER:__ Your action dice & WAR DICE are special D8s. They act as normal D8s except the 8s count as 0s. 6s & 7s on your dice count towards ultra successes. Double 0s are ultra failures.

- 2 weighted D6s (1 rolls 1s whilst the other rolls 6s)
- +1 WAR DIE at mission end

__MASKED:__ You have a mask permanently bonded to you that determines your masked identity. Your masked identity represents someone of high fame or infamy. It could be a prophet of a deity, a leader of a thieves guild, a reincarnation of a dead hero etc. Your masked identity is seen by all beings and deities as a separate being to your real identity. You can start a mission without the mask on but once on it cannot be removed till the current mission ends.  Anyone who saw you don the mask thinks you simply vanished and the masked identity must have come from somewhere else.

- Bonded mask
- +1 on any one attribute based on a strength of mask identity
- -1 on any one attribute based on a weakness of your real identity

__PRECOGNITION:__ At the start of a mission roll 3 D6s and mark down each number as a foresight number. At any point you may spend and use a foresight number by changing any rolled D6 to its number. Once all three foresight numbers are used you gain a fourth foresight number. You can choose what number (1, 2, 3, 4, 5, or 6) this fourth foresight number is when you use it.

- Tarot deck
- +1 TACTICAL

__STAR-BRAIN:__ Your mind is a mini-star. It is contained within a metal container that is your head. You have the following features:

1. __LIGHT:__ You can produce light. You can focus this light into a beam that deals (1D6+1 DAMAGE).
2. __GRAVITY:__ You can manipulate the gravity of your star either repelling or attracting objects to you.
3. __NOVA:__ If you unleash the star from your head, either voluntarily or involuntarily, it catastrophically unleashes light and heat dealing 4D6 damage to everything (except you) in a 20 foot radius (length of a standard cargo container). Afterwards your star is in a cooled down state, you are left with 1HP, and cannot use any feature of this trait till the end of the mission.

- Metal head (accessory)
- -2 CREATIVE

## Tartarus

__GRAVITY LIFT:__ You can create 1 gravity lift per mission. These cylinders  of reverse gravity can be up to the diameter of a normal bicycle wheel. The cylinder extends straight up from the centre of the celestial body you are on. The reverse gravity has the same force as the normal gravity from the celestial body.  The gravity lift lasts till you dismiss it or till the end of the mission.

- Stabilise and thrust boots (1 use, prevents fall damage)
- +1 TACTICAL

__KAIJU:__ You can transform into a kaiju no larger than a cargo container. When you choose this trait, also choose the form of your kaiju. You get the following when in your kaiju form:

1. Your total FORCEFUL score is +4 and your total REFLEXIVE score is -1. Your TACTICAL and CREATIVE are unchanged
2. You have a total HP of 20 and natural armor of 3
3. Your natural melee weapons deal 2D6 DAMAGE

All your gear is absorbed into your kaiju form so it cannot be used. 
When you return to normal you are wearing and wielding your gear normally. 
Your form lasts till you release it, you fail a skill check, your kaiju form reaches 0HP, or till the end of the mission. 
Any excess damage you take is suffered by your normal form. 

When you return to normal, reduce your FORCEFUL score by 1. You regain 1 FORCEFUL at the end of a mission. You cannot transform into your kaiju form if your current FORCEFUL score is -1 or less.

Instead of another level up reward you can choose one of the following kaiju upgrades. Each can only be chosen once.

1. Gain a ranged attack that deals 1D6+3 DAMAGE
2. Your natural melee weapons deal 4D6 DAMAGE
3. Your kaiju form size increases to that of a 3 bedroom house and you gain +10 HP 

- Life preserving airbag suit (accessory)
- -2 TACTICAL

__METAL EATER:__ You have extremely strong teeth and jaws. 
You are able to bite through small rocks & thin metal, such as wire metal fences, with no issue. 
If you attempt to bite or chew something larger or tougher your referee may ask you to roll a number of D6s equal to the amount of teeth you may lose. 
Each 1 or 2 rolled is a tooth that falls out. 
If you currently don’t have enough teeth you cannot make the attempt. 
At the end of a mission you regrow 1D6 missing teeth.

- A full set of 36 of your fallen out teeth
- +1 FORCEFUL

__PERCUSSIVE MAINTENANCE:__ You are an easily frustrated fixer. 
You can attempt to fix, unlock, hack etc., any mechanical or electronic device that is the size of a personal  computer or smaller with percussive maintenance. 
If so, roll a TACTICAL roll and a FORCEFUL roll. 
Resolve the higher of the 2 rolls. 
If the EYES is higher and successful you carry out the task based on the intention and the roll’s outcome. 
If the percussive maintenance roll (FORCEFUL) is higher you smash the device into pieces, a failed roll results in 1D6 DAMAGE to you.

- Large wrench (1D6 DAMAGE)
- +1 FORCEFUL

__PINBALL-WIZARD:__

You have complete control of up to 13 pinball sized metal ball bearings. 
You can make them fly or roll at high speeds.

- Bag of pinballs
- +2 CREATIVE

__STURDY:__ You can take more damage than the normal human. 
Your baseline HP is 8. 
If you have chosen HP upgrades in the past, reroll them using a D8 rather than the usual D6. 
Use D8 for all future HP gains. 

- Heavy riot shield (2 ARMOR, equip as weapon)
- -1 CREATIVE

## Proteus

__CHAKRAM PORTALS:__ You have 2 plate sized chakrams that are bonded to you.
They each have one perpetual portal as the hole. 
One portal is connected to the other. 
Once per mission you can turn off the portals for 1 second.

- Two portal chakrams (1D6+1 DAMAGE)
- +1 TACTICAL

__COMPOSITE:__ You can remove parts of your body. 
They act as if they are attached, fully under your control. 
No open wounds are created, the newly created inner surfaces are seemingly solid. 
Only you can remove and reattach these body parts.

- Box of surgical tape
- +1 REFELXIVE

__LIMBLESS:__ You have no limbs or neck. 
Instead your hands, feet, and head float. 
They mainly act as they would normally. 
You can move them closer or up to 2 times further than their normal distance relative to your body. 
You can violently fire a foot, hand, or your head taking 1 DAMAGE yourself. 
The extremity becomes detached and you will need to pick it up and bond it to you.

- Leather Spiked cap, gloves, and shoes (1D6 DAMAGE)
- -1 FORCEFUL

__NANOSUIT:__ You wear a skin tight nanosuit with nanobots flowing through your circulatory system. Your nanosuit has 6 charges. 
You can spend charges for the below special abilities.
Only one can be active at a time.

1. Attack (1 charge): +1 to an offence action roll and +2 to its DAMAGE
2. Defend (1 charge): +1 ARMOR till the end of the next combat phase
3. Cloak (3 charges): Gain invisibility for 6 - Threat level turns
4. Heal (3 charges): Gain +1D6HP

You may spend a level up to gain 6 more charges.

- Nanosuit (1 ARMOR, accessory)
- +3HP

__TRANSFORMER:__ Once per mission you can turn into a sentient vehicle. 
You can choose a vehicle with a HP value up to 8. 
You can control yourself, see, speak, and hear. 
You may choose one of the below upgrades instead of a normal level up reward. 
Each upgrade can only be chosen once. 

1. Increase HP of vehicle choice to 12HP
2. When you change into a vehicle roll once on the VEHICLE WEAPONS table to include the result on the vehicle you become

You revert back to normal when your vehicle form reaches 0HP or at the end of the mission. Any extra damage you receive when your vehicle form reaches 0HP is suffered by your normal form.

- Leather biker jacket (1 ARMOR)
- -1 CREATIVE

## Gaia

__COPY-AND-PASTE:__ You have multiple lives. 
For every 3HP you have you have 1 respawn (7 HP would be 3 respawns).
Each life has a HP of 3.
When you die you spawn in a place of your choice within 10 feet of your dead body, using one of your respawns. 
You are only wearing basic clothing, needing to retrieve your other gear from your dead body. 
If you die with 0 respawns your character is dead forever.

- Revolver (1D6+1 DAMAGE)
- +1 FORCEFUL

__ETTIN:__ You have 2 heads.
Whilst you have at least one head you will survive and grow back your second head.
You can spend one head as an accessory. 
Whilst you only have one head you gain +1 FORCEFUL and +1 REFLEXIVE, however you also gain -2 TACTICAL and -1 CREATIVE.

- Telescopic goggles and Bolt-action rifle (1d6+1 DAMAGE)
- +2 CREATIVE

__MICROBIOTA CONTROL:__ You are able to somewhat control the microbiota on and in your body (bacteria, archaea, & fungi). 
You can medicate yourself and are immune to ingested  poisons. 
Once per mission you can share your microbiome with one nearby target. 
This lasts as long as you both share the same air or the end of the current mission.

- Microbiology kit
- +1 CREATIVE

__MOTIVATIONAL SPEAKER:__ Your ability to encourage other borders on the supernatural. 
You can practically always make someone do something as long as they can hear & understand  you, and a decent chunk of them wants to do it.

- Tin foiled line hat (prevents all mental/psychic based attacks)
- +2 CREATIVE

__OVERGROWN:__ You are covered in ivy and various other plants. 
These plants are connected to you feeding off your nutrients as it shares its energy with you in a symbiotic relationship.
You may use the plants in various ways including as disguise and using the ivy to rappel with. 
Once per mission you can choose a type of plant to rapidly grow from you. 
As long as you survive the plants will always grow back at the end of a mission if they are somehow destroyed.

- Machete (1D6 DAMAGE)
- +1 CREATIVE

__POLYGLOT:__ You are fluent in the reading, writing, and speaking of 3 times your TACTICAL attribute additional  languages. 
You can also understand all other languages to a limited degree. 
When reading, writing, or communicating in a language you are not fluent in you and the referee can only speak with single syllable words. 
If you use a multi syllable word the referee may give you a complication.

- Remote covert listening device and headphone
- +2 TACTICAL

__SUITED-CREATURE:__ You are a small sentient living entity in a humanoid sized and shaped suit. 
You could be a worm in a suit from the gods, a little alien in a human robot, a goldfish in a fishbowl as the head of an iron golem etc. 
Choose what type of small entity you are and what type of suit you have. 
You may freely leave the suit. 
When you leave the suit you are still sentient and have 3HP.

- Robot suit (1 ARMOR)
- +1 REFLEXIVE








##