---
title: "CATALOG"
---

Links to various different places, fauna, and miscellaneous.

- [FOODCHAIN](/THE_RUSTLANDS/FOODCHAIN.qmd)
  - [FLYTOPLANKTON](/THE_RUSTLANDS/FOODCHAIN.qmd#flytoplankton)
  - [BURNACLES](/THE_RUSTLANDS/FOODCHAIN.qmd#burnacles)
- [RUSTPLAINS](/THE_RUSTLANDS/RUSTPLAINS.qmd)
  - [LEECH WORMS](/THE_RUSTLANDS/RUSTPLAINS.qmd#leechworms)
  - [WEATHER](/THE_RUSTLANDS/RUSTPLAINS.qmd#weather)
  - [EVENTS](/THE_RUSTLANDS/RUSTPLAINS.qmd#events)
- [LEMAN GROVE](/THE_RUSTLANDS/LEMAN_GROVE.qmd)
  - [LEMAN SERPENTS](/THE_RUSTLANDS/LEMAN_GROVE.qmd#lemanserpent)
  - [LEMAN WOODPECKERS](/THE_RUSTLANDS/LEMAN_GROVE.qmd#lemanwoodpecker)
  - [NOSEY MONKEYS](/THE_RUSTLANDS/LEMAN_GROVE.qmd#noseymonkeys)
- [WHALEFALL](/THE_RUSTLANDS/WHALEFALL.qmd)
  - [OCTONUT CRABS](/THE_RUSTLANDS/WHALEFALL.qmd#octonutcrabs)
  - [JUVENILE OCTONUT CRAB](/THE_RUSTLANDS/WHALEFALL.qmd#juvoctonutcrab)
  - [ADULT OCTONUT CRAB](/THE_RUSTLANDS/WHALEFALL.qmd#adultoctonutcrab)
  - [RUSTY HORSEHOSE CRABS](/THE_RUSTLANDS/WHALEFALL.qmd#rustyhorseshoecrabs)
- [THE GARDEN](/THE_RUSTLANDS/THE_GARDEN.qmd)
  - [OBSIDIAN LAVA TALOES](/THE_RUSTLANDS/THE_GARDEN.qmd#OBSIDANLAVATALOES)
  - [ABYSSAL BUTTERCUPS](/THE_RUSTLANDS/THE_GARDEN.qmd#abyssalbuttercup)
- [SKYSLIP](/THE_RUSTLANDS/SKYSLIP.qmd)
  - [CORAL MOAT](/THE_RUSTLANDS/SKYSLIP.qmd#coral-moat)
  - [ICEFISH](/THE_RUSTLANDS/SKYSLIP.qmd#ICEFISH)
  - [SKYSLIP YARD](/THE_RUSTLANDS/SKYSLIP.qmd#skyslip-yard)
  - [ICEFISH SPHERE](/THE_RUSTLANDS/SKYSLIP.qmd#icefishsphere)
  - [ARMOURED ICEFISH](/THE_RUSTLANDS/SKYSLIP.qmd#armouredicefish)